// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file gt2/vipTypes/vipTypes.proto (package vipTypes, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gt2/vipTypes/vipTypes.proto.
 */
export const file_gt2_vipTypes_vipTypes: GenFile = /*@__PURE__*/
  fileDesc("ChtndDIvdmlwVHlwZXMvdmlwVHlwZXMucHJvdG8SCHZpcFR5cGVzImkKFlVzZXJWaXBMZXZlbERldGFpbEluZm8SEQoJdmlwX2xldmVsGAEgASgNEjwKE3ZpcF9leHRyYV9yYXRlX2xpc3QYAiADKAsyHy52aXBUeXBlcy5Vc2VyVmlwTGV2ZWxFeHRyYVJhdGUiXwoVVXNlclZpcExldmVsRXh0cmFSYXRlEjgKCmV4dHJhX3R5cGUYASABKA4yJC52aXBUeXBlcy5Vc2VyVmlwRXh0cmFQYXJhbWV0ZXJzVHlwZRIMCgRyYXRlGAIgASgCKrcCChpVc2VyVmlwRXh0cmFQYXJhbWV0ZXJzVHlwZRIYChRVU0VSX1ZJUF9FWFRSQV9VTkRFRhAAEiQKIFVTRVJfVklQX0VYVFJBX0NPSU5fUEFDS0FHRV9SQVRFEAESJwojVVNFUl9WSVBfRVhUUkFfU1BFQ0lBTF9TSUdOX0lOX1JBVEUQAhIjCh9VU0VSX1ZJUF9FWFRSQV9EQUlMWV9CT05VU19SQVRFEAMSIwofVVNFUl9WSVBfRVhUUkFfTE9CQllfQk9OVVNfUkFURRAEEiMKH1VTRVJfVklQX0VYVFJBX0RBSUxZX1dIRUVMX1JBVEUQBRIpCiVVU0VSX1ZJUF9FWFRSQV9KT1VSTkVZX0FMQlVNX1NFTkRfTlVNEAcSFgoSVVNFUl9WSVBfRVhUUkFfTUFYEAhCfwoMY29tLnZpcFR5cGVzQg1WaXBUeXBlc1Byb3RvUAFaIHByb3RvY29sL2d0Mi92aXBUeXBlczt2aXBUeXBlc1BiogIDVlhYqgIIVmlwVHlwZXPKAghWaXBUeXBlc+ICFFZpcFR5cGVzXEdQQk1ldGFkYXRh6gIIVmlwVHlwZXNiBnByb3RvMw");

/**
 * @generated from message vipTypes.UserVipLevelDetailInfo
 */
export type UserVipLevelDetailInfo = Message<"vipTypes.UserVipLevelDetailInfo"> & {
  /**
   * @generated from field: uint32 vip_level = 1;
   */
  vipLevel: number;

  /**
   * @generated from field: repeated vipTypes.UserVipLevelExtraRate vip_extra_rate_list = 2;
   */
  vipExtraRateList: UserVipLevelExtraRate[];
};

/**
 * Describes the message vipTypes.UserVipLevelDetailInfo.
 * Use `create(UserVipLevelDetailInfoSchema)` to create a new message.
 */
export const UserVipLevelDetailInfoSchema: GenMessage<UserVipLevelDetailInfo> = /*@__PURE__*/
  messageDesc(file_gt2_vipTypes_vipTypes, 0);

/**
 * @generated from message vipTypes.UserVipLevelExtraRate
 */
export type UserVipLevelExtraRate = Message<"vipTypes.UserVipLevelExtraRate"> & {
  /**
   * @generated from field: vipTypes.UserVipExtraParametersType extra_type = 1;
   */
  extraType: UserVipExtraParametersType;

  /**
   * @generated from field: float rate = 2;
   */
  rate: number;
};

/**
 * Describes the message vipTypes.UserVipLevelExtraRate.
 * Use `create(UserVipLevelExtraRateSchema)` to create a new message.
 */
export const UserVipLevelExtraRateSchema: GenMessage<UserVipLevelExtraRate> = /*@__PURE__*/
  messageDesc(file_gt2_vipTypes_vipTypes, 1);

/**
 * @generated from enum vipTypes.UserVipExtraParametersType
 */
export enum UserVipExtraParametersType {
  /**
   * @generated from enum value: USER_VIP_EXTRA_UNDEF = 0;
   */
  USER_VIP_EXTRA_UNDEF = 0,

  /**
   * 儲值加成倍率
   *
   * @generated from enum value: USER_VIP_EXTRA_COIN_PACKAGE_RATE = 1;
   */
  USER_VIP_EXTRA_COIN_PACKAGE_RATE = 1,

  /**
   * 特殊簽到加成倍率
   *
   * @generated from enum value: USER_VIP_EXTRA_SPECIAL_SIGN_IN_RATE = 2;
   */
  USER_VIP_EXTRA_SPECIAL_SIGN_IN_RATE = 2,

  /**
   * 簽到加成倍率
   *
   * @generated from enum value: USER_VIP_EXTRA_DAILY_BONUS_RATE = 3;
   */
  USER_VIP_EXTRA_DAILY_BONUS_RATE = 3,

  /**
   * 離線獎勵加成倍率
   *
   * @generated from enum value: USER_VIP_EXTRA_LOBBY_BONUS_RATE = 4;
   */
  USER_VIP_EXTRA_LOBBY_BONUS_RATE = 4,

  /**
   * 離線獎勵轉輪加成倍率
   *
   * @generated from enum value: USER_VIP_EXTRA_DAILY_WHEEL_RATE = 5;
   */
  USER_VIP_EXTRA_DAILY_WHEEL_RATE = 5,

  /**
   * 6 : 優先使用
   *
   * 卡冊贈送次數
   *
   * @generated from enum value: USER_VIP_EXTRA_JOURNEY_ALBUM_SEND_NUM = 7;
   */
  USER_VIP_EXTRA_JOURNEY_ALBUM_SEND_NUM = 7,

  /**
   * 擺在最後, 值 : 永遠等於最後一個類型+1
   *
   * @generated from enum value: USER_VIP_EXTRA_MAX = 8;
   */
  USER_VIP_EXTRA_MAX = 8,
}

/**
 * Describes the enum vipTypes.UserVipExtraParametersType.
 */
export const UserVipExtraParametersTypeSchema: GenEnum<UserVipExtraParametersType> = /*@__PURE__*/
  enumDesc(file_gt2_vipTypes_vipTypes, 0);

