// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file service/statement/statement.proto (package statement, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Balance } from "../../gt2/currency/currency_pb";
import { file_gt2_currency_currency } from "../../gt2/currency/currency_pb";
import type { Type } from "../../gt2/lct/lct_pb";
import { file_gt2_lct_lct } from "../../gt2/lct/lct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/statement/statement.proto.
 */
export const file_service_statement_statement: GenFile = /*@__PURE__*/
  fileDesc("CiFzZXJ2aWNlL3N0YXRlbWVudC9zdGF0ZW1lbnQucHJvdG8SCXN0YXRlbWVudCKYAQoNQ3VycmVuY3lOb3RpZhIwCgdjaGFuZ2VzGAEgAygLMh8uc3RhdGVtZW50LkN1cnJlbmN5Tm90aWYuQ2hhbmdlGlUKBkNoYW5nZRIiCgdiYWxhbmNlGAEgASgLMhEuY3VycmVuY3kuQmFsYW5jZRIMCgRkaWZmGAIgASgDEhkKBnJlYXNvbhgDIAEoDjIJLmxjdC5UeXBlKigKA1MyVRIPCgtTMlVfVU5LTk9XThAAEhAKDFMyVV9DVVJSRU5DWRABQosBCg1jb20uc3RhdGVtZW50Qg5TdGF0ZW1lbnRQcm90b1ABWiZwcm90b2NvbC9zZXJ2aWNlL3N0YXRlbWVudDtzdGF0ZW1lbnRQYqICA1NYWKoCCVN0YXRlbWVudMoCCVN0YXRlbWVudOICFVN0YXRlbWVudFxHUEJNZXRhZGF0YeoCCVN0YXRlbWVudGIGcHJvdG8z", [file_gt2_currency_currency, file_gt2_lct_lct]);

/**
 * @generated from message statement.CurrencyNotif
 */
export type CurrencyNotif = Message<"statement.CurrencyNotif"> & {
  /**
   * @generated from field: repeated statement.CurrencyNotif.Change changes = 1;
   */
  changes: CurrencyNotif_Change[];
};

/**
 * Describes the message statement.CurrencyNotif.
 * Use `create(CurrencyNotifSchema)` to create a new message.
 */
export const CurrencyNotifSchema: GenMessage<CurrencyNotif> = /*@__PURE__*/
  messageDesc(file_service_statement_statement, 0);

/**
 * @generated from message statement.CurrencyNotif.Change
 */
export type CurrencyNotif_Change = Message<"statement.CurrencyNotif.Change"> & {
  /**
   * @generated from field: currency.Balance balance = 1;
   */
  balance?: Balance;

  /**
   * gt2.Money
   *
   * @generated from field: int64 diff = 2;
   */
  diff: bigint;

  /**
   * @generated from field: lct.Type reason = 3;
   */
  reason: Type;
};

/**
 * Describes the message statement.CurrencyNotif.Change.
 * Use `create(CurrencyNotif_ChangeSchema)` to create a new message.
 */
export const CurrencyNotif_ChangeSchema: GenMessage<CurrencyNotif_Change> = /*@__PURE__*/
  messageDesc(file_service_statement_statement, 0, 0);

/**
 * @generated from enum statement.S2U
 */
export enum S2U {
  /**
   * @generated from enum value: S2U_UNKNOWN = 0;
   */
  S2U_UNKNOWN = 0,

  /**
   * CurrencyNotif
   *
   * @generated from enum value: S2U_CURRENCY = 1;
   */
  S2U_CURRENCY = 1,
}

/**
 * Describes the enum statement.S2U.
 */
export const S2USchema: GenEnum<S2U> = /*@__PURE__*/
  enumDesc(file_service_statement_statement, 0);

