// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file service/login/login.proto (package login, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { UserClientType, WebDomainType } from "../../gt2/userTypes/userTypes_pb";
import { file_gt2_userTypes_userTypes } from "../../gt2/userTypes/userTypes_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/login/login.proto.
 */
export const file_service_login_login: GenFile = /*@__PURE__*/
  fileDesc("ChlzZXJ2aWNlL2xvZ2luL2xvZ2luLnByb3RvEgVsb2dpbiLvAQoQTG9naW5SZXF1ZXN0RGF0YRIQCgh1c2VybmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCRIKCgJsYxgDIAEoCRISCgphcHBWZXJzaW9uGAQgASgJEhAKCGRldmljZUlkGAUgASgJEjEKDnVzZXJDbGllbnRUeXBlGAYgASgOMhkudXNlclR5cGVzLlVzZXJDbGllbnRUeXBlEi8KDXdlYkRvbWFpblR5cGUYByABKA4yGC51c2VyVHlwZXMuV2ViRG9tYWluVHlwZRIQCghwYXNzQ29kZRgIIAEoDRIPCgdwYXNzS2V5GAkgASgJIm4KDExvZ2luQWNrRGF0YRIqCgpwZXJtaXNzaW9uGAEgASgOMhYubG9naW4uUEVSTUlTU0lPTl9UWVBFEhEKCWFjY291bnRJZBgCIAEoDRIQCgh1c2VybmFtZRgDIAEoCRINCgV0b2tlbhgEIAEoCSoUCgNVMlMSDQoJTE9HSU5fUkVREAAqFAoDUzJVEg0KCUxPR0lOX0FDSxAAKsoECg9QRVJNSVNTSU9OX1RZUEUSDQoJTk9UX1JFQURZEAASBgoCT0sQARIQCgxVTktOT1dOX1VTRVIQAhINCglEVVBMSUNBVEUQAxITCg9JTlZBTElEX0FDQ09VTlQQBBIRCg1BQ0NFU1NfREVOSUVEEAUSFQoRQ09OTkVDVElPTl9GQUlMRUQQBhINCglVU0VSX0ZVTEwQCBISCg5WRVJTSU9OX0ZBSUxFRBAJEhMKD0FDQ09VTlRfRElTQUJMRRAKEg0KCVVOREVGSU5FRBALEhEKDUNPTU1BTkRfRVJST1IQDBIZChRFTkNSWVBUSU9OX0RJU0FHUkVFRBD3ARIWChJVU0VSX05BTUVfSVNfRU1QVFkQFBIaChZVU0VSX0lQX0lTX05PVF9BTExPV0VEEBUSFQoRQ0hFQ0tfS0VZX0lTX1pFUk8QFhIWChJEVVBMSUNBVEVfUExBVEZPUk0QHBIUChBSRUxPR0lOX1RPT19GQVNUECESFAoQSFNfQ09ERV9SRVFVSVJFRBAiEhgKFE1BQ09ERV9ERUNPREVfRkFJTEVEECQSFwoTSFNfTlVNX0NIRUNLX0ZBSUxFRBAlEhYKEkhTX0xDX0NIRUNLX0ZBSUxFRBAmEg4KCkFDQ09VTlRfSEsQMhIPCgtGT1JDRV9MRUFWRRAzEhYKEkZPUkNFX0xFQVZFX0ZBSUxFRBA0EhQKEElOX1JFU1RSSUNUX01PREUQNRIiCh5GUk9NX0JBU0VfUkVDT05ORUNUX1NVQ0NFU1NGVUwQKEJrCgljb20ubG9naW5CCkxvZ2luUHJvdG9QAVoecHJvdG9jb2wvc2VydmljZS9sb2dpbjtsb2dpblBiogIDTFhYqgIFTG9naW7KAgVMb2dpbuICEUxvZ2luXEdQQk1ldGFkYXRh6gIFTG9naW5iBnByb3RvMw", [file_gt2_userTypes_userTypes]);

/**
 * *
 * 登入請求數據
 *
 * @generated from message login.LoginRequestData
 */
export type LoginRequestData = Message<"login.LoginRequestData"> & {
  /**
   * 基本登入資訊
   *
   * 用戶名 (或 LC前17字)
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * 密碼 (或 LC後15字)
   *
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * LC認證碼(or HS驗證碼)
   *
   * @generated from field: string lc = 3;
   */
  lc: string;

  /**
   * 應用程式版本 gt2.Version(0.0.0.0)
   *
   * @generated from field: string appVersion = 4;
   */
  appVersion: string;

  /**
   * 裝置和用戶端資訊
   *
   * 裝置ID
   *
   * @generated from field: string deviceId = 5;
   */
  deviceId: string;

  /**
   * 用戶裝置類型
   *
   * @generated from field: userTypes.UserClientType userClientType = 6;
   */
  userClientType: UserClientType;

  /**
   * 用戶端網域ID
   *
   * @generated from field: userTypes.WebDomainType webDomainType = 7;
   */
  webDomainType: WebDomainType;

  /**
   * VerifyCode相關驗證機制
   *
   * 認證碼
   *
   * @generated from field: uint32 passCode = 8;
   */
  passCode: number;

  /**
   * 認證碼金鑰
   *
   * @generated from field: string passKey = 9;
   */
  passKey: string;
};

/**
 * Describes the message login.LoginRequestData.
 * Use `create(LoginRequestDataSchema)` to create a new message.
 */
export const LoginRequestDataSchema: GenMessage<LoginRequestData> = /*@__PURE__*/
  messageDesc(file_service_login_login, 0);

/**
 * *
 * 登入回應數據
 *
 * @generated from message login.LoginAckData
 */
export type LoginAckData = Message<"login.LoginAckData"> & {
  /**
   * 認證結果
   *
   * 權限狀態
   *
   * @generated from field: login.PERMISSION_TYPE permission = 1;
   */
  permission: PERMISSION_TYPE;

  /**
   * 帳號ID
   *
   * @generated from field: uint32 accountId = 2;
   */
  accountId: number;

  /**
   * 用戶名
   *
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * 授權令牌
   *
   * @generated from field: string token = 4;
   */
  token: string;
};

/**
 * Describes the message login.LoginAckData.
 * Use `create(LoginAckDataSchema)` to create a new message.
 */
export const LoginAckDataSchema: GenMessage<LoginAckData> = /*@__PURE__*/
  messageDesc(file_service_login_login, 1);

/**
 * U2S 命令
 *
 * @generated from enum login.U2S
 */
export enum U2S {
  /**
   * LoginRequestData  // 登入請求
   *
   * @generated from enum value: LOGIN_REQ = 0;
   */
  LOGIN_REQ = 0,
}

/**
 * Describes the enum login.U2S.
 */
export const U2SSchema: GenEnum<U2S> = /*@__PURE__*/
  enumDesc(file_service_login_login, 0);

/**
 * S2U 命令
 *
 * @generated from enum login.S2U
 */
export enum S2U {
  /**
   * LoginAckData      // 登入回應
   *
   * @generated from enum value: LOGIN_ACK = 0;
   */
  LOGIN_ACK = 0,
}

/**
 * Describes the enum login.S2U.
 */
export const S2USchema: GenEnum<S2U> = /*@__PURE__*/
  enumDesc(file_service_login_login, 1);

/**
 * *
 * Permission Types - 權限狀態碼
 *
 * @generated from enum login.PERMISSION_TYPE
 */
export enum PERMISSION_TYPE {
  /**
   * 基本狀態
   *
   * 等待中
   *
   * @generated from enum value: NOT_READY = 0;
   */
  NOT_READY = 0,

  /**
   * 權限正常
   *
   * @generated from enum value: OK = 1;
   */
  OK = 1,

  /**
   * 未知使用者
   *
   * @generated from enum value: UNKNOWN_USER = 2;
   */
  UNKNOWN_USER = 2,

  /**
   * 已在線上
   *
   * @generated from enum value: DUPLICATE = 3;
   */
  DUPLICATE = 3,

  /**
   * 無效帳號
   *
   * @generated from enum value: INVALID_ACCOUNT = 4;
   */
  INVALID_ACCOUNT = 4,

  /**
   * 密碼錯誤
   *
   * @generated from enum value: ACCESS_DENIED = 5;
   */
  ACCESS_DENIED = 5,

  /**
   * 連線失敗
   *
   * @generated from enum value: CONNECTION_FAILED = 6;
   */
  CONNECTION_FAILED = 6,

  /**
   * 使用者已滿
   *
   * @generated from enum value: USER_FULL = 8;
   */
  USER_FULL = 8,

  /**
   * 版本錯誤
   *
   * @generated from enum value: VERSION_FAILED = 9;
   */
  VERSION_FAILED = 9,

  /**
   * 帳號停止使用
   *
   * @generated from enum value: ACCOUNT_DISABLE = 10;
   */
  ACCOUNT_DISABLE = 10,

  /**
   * 未定義狀態
   *
   * @generated from enum value: UNDEFINED = 11;
   */
  UNDEFINED = 11,

  /**
   * 命令錯誤
   *
   * @generated from enum value: COMMAND_ERROR = 12;
   */
  COMMAND_ERROR = 12,

  /**
   * 偵錯階段
   *
   * 加密協定不一致
   *
   * @generated from enum value: ENCRYPTION_DISAGREED = 247;
   */
  ENCRYPTION_DISAGREED = 247,

  /**
   * GT2 特定
   *
   * 使用者名稱為空
   *
   * @generated from enum value: USER_NAME_IS_EMPTY = 20;
   */
  USER_NAME_IS_EMPTY = 20,

  /**
   * 使用者IP不允許
   *
   * @generated from enum value: USER_IP_IS_NOT_ALLOWED = 21;
   */
  USER_IP_IS_NOT_ALLOWED = 21,

  /**
   * 檢查金鑰為零
   *
   * @generated from enum value: CHECK_KEY_IS_ZERO = 22;
   */
  CHECK_KEY_IS_ZERO = 22,

  /**
   * 新舊平台重複登入
   *
   * @generated from enum value: DUPLICATE_PLATFORM = 28;
   */
  DUPLICATE_PLATFORM = 28,

  /**
   * 重新登入太快
   *
   * @generated from enum value: RELOGIN_TOO_FAST = 33;
   */
  RELOGIN_TOO_FAST = 33,

  /**
   * 需要HS驗證碼
   *
   * @generated from enum value: HS_CODE_REQUIRED = 34;
   */
  HS_CODE_REQUIRED = 34,

  /**
   * MACode解碼失敗
   *
   * @generated from enum value: MACODE_DECODE_FAILED = 36;
   */
  MACODE_DECODE_FAILED = 36,

  /**
   * HS驗證碼檢查失敗
   *
   * @generated from enum value: HS_NUM_CHECK_FAILED = 37;
   */
  HS_NUM_CHECK_FAILED = 37,

  /**
   * HS驗證碼LC檢查失敗
   *
   * @generated from enum value: HS_LC_CHECK_FAILED = 38;
   */
  HS_LC_CHECK_FAILED = 38,

  /**
   * 帳號相關
   *
   * 港版帳號
   *
   * @generated from enum value: ACCOUNT_HK = 50;
   */
  ACCOUNT_HK = 50,

  /**
   * 強制登入, 將原先登入的帳號做 Logout 的動作
   *
   * @generated from enum value: FORCE_LEAVE = 51;
   */
  FORCE_LEAVE = 51,

  /**
   * 強制登入失敗
   *
   * @generated from enum value: FORCE_LEAVE_FAILED = 52;
   */
  FORCE_LEAVE_FAILED = 52,

  /**
   * 維修模式
   *
   * @generated from enum value: IN_RESTRICT_MODE = 53;
   */
  IN_RESTRICT_MODE = 53,

  /**
   * 僅用於Login日誌
   *
   * 從Base重連成功
   *
   * @generated from enum value: FROM_BASE_RECONNECT_SUCCESSFUL = 40;
   */
  FROM_BASE_RECONNECT_SUCCESSFUL = 40,
}

/**
 * Describes the enum login.PERMISSION_TYPE.
 */
export const PERMISSION_TYPESchema: GenEnum<PERMISSION_TYPE> = /*@__PURE__*/
  enumDesc(file_service_login_login, 2);

