// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file game/common/common.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file game/common/common.proto.
 */
export const file_game_common_common: GenFile = /*@__PURE__*/
  fileDesc("ChhnYW1lL2NvbW1vbi9jb21tb24ucHJvdG8SBmNvbW1vbiJMCgdCZXRJbmZvEhAKCGJldEluZGV4GAEgASgFEgsKA2JldBgCIAEoAxIQCghtaW5MZXZlbBgDIAEoDRIQCghtYXhMZXZlbBgEIAEoDSJCCglKcFNldHRpbmcSDwoHanBfdHlwZRgBIAEoDRIRCgliYXNlX29kZHMYAiABKA0SEQoJZHJhd19yYXRlGAMgASgBIkQKClVubG9ja0luZm8SEwoLdW5sb2NrX3R5cGUYASABKAUSCwoDYmV0GAIgASgDEhQKDHVubG9ja19sZXZlbBgDIAEoDSKcAQoTQ29tbW9uQ21kQmV0U2V0dGluZxIhCghiZXRfbGlzdBgBIAMoCzIPLmNvbW1vbi5CZXRJbmZvEiIKB2pwX2xpc3QYAiADKAsyES5jb21tb24uSnBTZXR0aW5nEicKC3VubG9ja19saXN0GAMgAygLMhIuY29tbW9uLlVubG9ja0luZm8SFQoNYmV0X3VubG9ja190cxgEIAEoAyJdCg5Db21tb25HYW1lSW5mbxIiCgdqcF9saXN0GAEgAygLMhEuY29tbW9uLkpwU2V0dGluZxInCgt1bmxvY2tfbGlzdBgCIAMoCzISLmNvbW1vbi5VbmxvY2tJbmZvIiYKDUNvbW1vblNwaW5SZXESFQoNYmV0X3VubG9ja190cxgBIAEoAyIPCg1Db21tb25TcGluQWNrKnMKA1UyRxITCg9VMkdfQ09NTU9OX05PTkUQABIZChRVMkdfQ09NTU9OX0NNRF9CRUdJThDIARIjCh5VMkdfQ09NTU9OX0NNRF9CRVRfU0VUVElOR19SRVEQyQESFwoSVTJHX0NPTU1PTl9DTURfTUFYEP8BKnMKA0cyVRITCg9HMlVfQ09NTU9OX05PTkUQABIZChRHMlVfQ09NTU9OX0NNRF9CRUdJThDIARIjCh5HMlVfQ09NTU9OX0NNRF9CRVRfU0VUVElOR19BQ0sQyQESFwoSRzJVX0NPTU1PTl9DTURfTUFYEP8BQnAKCmNvbS5jb21tb25CC0NvbW1vblByb3RvUAFaHXByb3RvY29sL2dhbWUvY29tbW9uO2NvbW1vblBiogIDQ1hYqgIGQ29tbW9uygIGQ29tbW9u4gISQ29tbW9uXEdQQk1ldGFkYXRh6gIGQ29tbW9uYgZwcm90bzM");

/**
 * 押注設定
 *
 * @generated from message common.BetInfo
 */
export type BetInfo = Message<"common.BetInfo"> & {
  /**
   * 押注索引
   *
   * @generated from field: int32 betIndex = 1;
   */
  betIndex: number;

  /**
   * 押注
   *
   * @generated from field: int64 bet = 2;
   */
  bet: bigint;

  /**
   * 最小等級
   *
   * @generated from field: uint32 minLevel = 3;
   */
  minLevel: number;

  /**
   * 最大等級
   *
   * @generated from field: uint32 maxLevel = 4;
   */
  maxLevel: number;
};

/**
 * Describes the message common.BetInfo.
 * Use `create(BetInfoSchema)` to create a new message.
 */
export const BetInfoSchema: GenMessage<BetInfo> = /*@__PURE__*/
  messageDesc(file_game_common_common, 0);

/**
 * @generated from message common.JpSetting
 */
export type JpSetting = Message<"common.JpSetting"> & {
  /**
   * Jp 類型
   *
   * @generated from field: uint32 jp_type = 1;
   */
  jpType: number;

  /**
   * 押注倍數
   *
   * @generated from field: uint32 base_odds = 2;
   */
  baseOdds: number;

  /**
   * 押注抽取%數
   *
   * @generated from field: double draw_rate = 3;
   */
  drawRate: number;
};

/**
 * Describes the message common.JpSetting.
 * Use `create(JpSettingSchema)` to create a new message.
 */
export const JpSettingSchema: GenMessage<JpSetting> = /*@__PURE__*/
  messageDesc(file_game_common_common, 1);

/**
 * 解鎖設定
 *
 * @generated from message common.UnlockInfo
 */
export type UnlockInfo = Message<"common.UnlockInfo"> & {
  /**
   * 解鎖類型
   *
   * @generated from field: int32 unlock_type = 1;
   */
  unlockType: number;

  /**
   * 押注
   *
   * @generated from field: int64 bet = 2;
   */
  bet: bigint;

  /**
   * 解鎖等級
   *
   * @generated from field: uint32 unlock_level = 3;
   */
  unlockLevel: number;
};

/**
 * Describes the message common.UnlockInfo.
 * Use `create(UnlockInfoSchema)` to create a new message.
 */
export const UnlockInfoSchema: GenMessage<UnlockInfo> = /*@__PURE__*/
  messageDesc(file_game_common_common, 2);

/**
 * 押注與解鎖設定
 *
 * @generated from message common.CommonCmdBetSetting
 */
export type CommonCmdBetSetting = Message<"common.CommonCmdBetSetting"> & {
  /**
   * 押注設定
   *
   * @generated from field: repeated common.BetInfo bet_list = 1;
   */
  betList: BetInfo[];

  /**
   * JP 設定
   *
   * @generated from field: repeated common.JpSetting jp_list = 2;
   */
  jpList: JpSetting[];

  /**
   * 解鎖設定
   *
   * @generated from field: repeated common.UnlockInfo unlock_list = 3;
   */
  unlockList: UnlockInfo[];

  /**
   * 押注解鎖設定時間戳( TimeStamp )
   *
   * @generated from field: int64 bet_unlock_ts = 4;
   */
  betUnlockTs: bigint;
};

/**
 * Describes the message common.CommonCmdBetSetting.
 * Use `create(CommonCmdBetSettingSchema)` to create a new message.
 */
export const CommonCmdBetSettingSchema: GenMessage<CommonCmdBetSetting> = /*@__PURE__*/
  messageDesc(file_game_common_common, 3);

/**
 * 通用遊戲資訊
 *
 * @generated from message common.CommonGameInfo
 */
export type CommonGameInfo = Message<"common.CommonGameInfo"> & {
  /**
   * JP 設定
   *
   * @generated from field: repeated common.JpSetting jp_list = 1;
   */
  jpList: JpSetting[];

  /**
   * 獎項與解鎖設定( 斷線重連才需要傳 )
   *
   * @generated from field: repeated common.UnlockInfo unlock_list = 2;
   */
  unlockList: UnlockInfo[];
};

/**
 * Describes the message common.CommonGameInfo.
 * Use `create(CommonGameInfoSchema)` to create a new message.
 */
export const CommonGameInfoSchema: GenMessage<CommonGameInfo> = /*@__PURE__*/
  messageDesc(file_game_common_common, 4);

/**
 * 通用遊戲資訊
 *
 * @generated from message common.CommonSpinReq
 */
export type CommonSpinReq = Message<"common.CommonSpinReq"> & {
  /**
   * 押注解鎖設定時間戳( TimeStamp )
   *
   * @generated from field: int64 bet_unlock_ts = 1;
   */
  betUnlockTs: bigint;
};

/**
 * Describes the message common.CommonSpinReq.
 * Use `create(CommonSpinReqSchema)` to create a new message.
 */
export const CommonSpinReqSchema: GenMessage<CommonSpinReq> = /*@__PURE__*/
  messageDesc(file_game_common_common, 5);

/**
 * 通用遊戲資訊
 *
 * @generated from message common.CommonSpinAck
 */
export type CommonSpinAck = Message<"common.CommonSpinAck"> & {
};

/**
 * Describes the message common.CommonSpinAck.
 * Use `create(CommonSpinAckSchema)` to create a new message.
 */
export const CommonSpinAckSchema: GenMessage<CommonSpinAck> = /*@__PURE__*/
  messageDesc(file_game_common_common, 6);

/**
 * U2G 
 *
 * @generated from enum common.U2G
 */
export enum U2G {
  /**
   * @generated from enum value: U2G_COMMON_NONE = 0;
   */
  U2G_COMMON_NONE = 0,

  /**
   * @generated from enum value: U2G_COMMON_CMD_BEGIN = 200;
   */
  U2G_COMMON_CMD_BEGIN = 200,

  /**
   * 押注設定請求
   *
   * @generated from enum value: U2G_COMMON_CMD_BET_SETTING_REQ = 201;
   */
  U2G_COMMON_CMD_BET_SETTING_REQ = 201,

  /**
   * @generated from enum value: U2G_COMMON_CMD_MAX = 255;
   */
  U2G_COMMON_CMD_MAX = 255,
}

/**
 * Describes the enum common.U2G.
 */
export const U2GSchema: GenEnum<U2G> = /*@__PURE__*/
  enumDesc(file_game_common_common, 0);

/**
 * G2U
 *
 * @generated from enum common.G2U
 */
export enum G2U {
  /**
   * @generated from enum value: G2U_COMMON_NONE = 0;
   */
  G2U_COMMON_NONE = 0,

  /**
   * @generated from enum value: G2U_COMMON_CMD_BEGIN = 200;
   */
  G2U_COMMON_CMD_BEGIN = 200,

  /**
   * 押注設定回應
   *
   * @generated from enum value: G2U_COMMON_CMD_BET_SETTING_ACK = 201;
   */
  G2U_COMMON_CMD_BET_SETTING_ACK = 201,

  /**
   * @generated from enum value: G2U_COMMON_CMD_MAX = 255;
   */
  G2U_COMMON_CMD_MAX = 255,
}

/**
 * Describes the enum common.G2U.
 */
export const G2USchema: GenEnum<G2U> = /*@__PURE__*/
  enumDesc(file_game_common_common, 1);

