// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file gt2/currency/currency.proto (package currency, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gt2/currency/currency.proto.
 */
export const file_gt2_currency_currency: GenFile = /*@__PURE__*/
  fileDesc("ChtndDIvY3VycmVuY3kvY3VycmVuY3kucHJvdG8SCGN1cnJlbmN5Ii0KBkNyZWRpdBIjCghiYWxhbmNlcxgBIAMoCzIRLmN1cnJlbmN5LkJhbGFuY2UiNwoHQmFsYW5jZRIcCgR0eXBlGAEgASgOMg4uY3VycmVuY3kuVHlwZRIOCgZhbW91bnQYAiABKAMq8AMKBFR5cGUSEAoMVFlQRV9JTlZBTElEEAASDgoKVFlQRV9JQ09JThABEhAKDFRZUEVfRElBTU9ORBACEhIKDlRZUEVfTkVXX0JFR0lOEDMSFAoQVFlQRV9TVE9ORV9CRUdJThAzEhQKEFRZUEVfU1VQRVJfU1RPTkUQMxIWChJUWVBFX0xfU1VQRVJfU1RPTkUQNBITCg9UWVBFX0hJR0hfU1RPTkUQNRIVChFUWVBFX0xfSElHSF9TVE9ORRA2Eg4KClRZUEVfU1RPTkUQNxIQCgxUWVBFX0xfU1RPTkUQOBIXChNUWVBFX0xfUk9PS0lFX1NUT05FEDkSFQoRVFlQRV9MX01JTklfU1RPTkUQOhISCg5UWVBFX1NUT05FX0VORBA7EhYKElRZUEVfV0FSSEVBRF9CRUdJThA8EhYKElRZUEVfU1VQRVJfV0FSSEVBRBA8EhgKFFRZUEVfTF9TVVBFUl9XQVJIRUFEED0SFQoRVFlQRV9ISUdIX1dBUkhFQUQQPhIXChNUWVBFX0xfSElHSF9XQVJIRUFEED8SEAoMVFlQRV9XQVJIRUFEEEASEgoOVFlQRV9MX1dBUkhFQUQQQRIUChBUWVBFX1dBUkhFQURfRU5EEEISEAoMVFlQRV9DUllTVEFMEEYaAhABQn8KDGNvbS5jdXJyZW5jeUINQ3VycmVuY3lQcm90b1ABWiBwcm90b2NvbC9ndDIvY3VycmVuY3k7Y3VycmVuY3lQYqICA0NYWKoCCEN1cnJlbmN5ygIIQ3VycmVuY3niAhRDdXJyZW5jeVxHUEJNZXRhZGF0YeoCCEN1cnJlbmN5YgZwcm90bzM");

/**
 * @generated from message currency.Credit
 */
export type Credit = Message<"currency.Credit"> & {
  /**
   * @generated from field: repeated currency.Balance balances = 1;
   */
  balances: Balance[];
};

/**
 * Describes the message currency.Credit.
 * Use `create(CreditSchema)` to create a new message.
 */
export const CreditSchema: GenMessage<Credit> = /*@__PURE__*/
  messageDesc(file_gt2_currency_currency, 0);

/**
 * @generated from message currency.Balance
 */
export type Balance = Message<"currency.Balance"> & {
  /**
   * currency.Type
   *
   * @generated from field: currency.Type type = 1;
   */
  type: Type;

  /**
   * gt2.Money
   *
   * @generated from field: int64 amount = 2;
   */
  amount: bigint;
};

/**
 * Describes the message currency.Balance.
 * Use `create(BalanceSchema)` to create a new message.
 */
export const BalanceSchema: GenMessage<Balance> = /*@__PURE__*/
  messageDesc(file_gt2_currency_currency, 1);

/**
 * @generated from enum currency.Type
 */
export enum Type {
  /**
   * @generated from enum value: TYPE_INVALID = 0;
   */
  INVALID = 0,

  /**
   * i幣
   *
   * @generated from enum value: TYPE_ICOIN = 1;
   */
  ICOIN = 1,

  /**
   * 鑽石
   *
   * @generated from enum value: TYPE_DIAMOND = 2;
   */
  DIAMOND = 2,

  /**
   * @generated from enum value: TYPE_NEW_BEGIN = 51;
   */
  NEW_BEGIN = 51,

  /**
   * @generated from enum value: TYPE_STONE_BEGIN = 51;
   */
  STONE_BEGIN = 51,

  /**
   * 超能武石
   *
   * @generated from enum value: TYPE_SUPER_STONE = 51;
   */
  SUPER_STONE = 51,

  /**
   * 超能武石(綁定)
   *
   * @generated from enum value: TYPE_L_SUPER_STONE = 52;
   */
  L_SUPER_STONE = 52,

  /**
   * 高能武石
   *
   * @generated from enum value: TYPE_HIGH_STONE = 53;
   */
  HIGH_STONE = 53,

  /**
   * 高能武石(綁定)
   *
   * @generated from enum value: TYPE_L_HIGH_STONE = 54;
   */
  L_HIGH_STONE = 54,

  /**
   * 能量武石
   *
   * @generated from enum value: TYPE_STONE = 55;
   */
  STONE = 55,

  /**
   * 能量武石(綁定)
   *
   * @generated from enum value: TYPE_L_STONE = 56;
   */
  L_STONE = 56,

  /**
   * 新手能量武石(綁定)
   *
   * @generated from enum value: TYPE_L_ROOKIE_STONE = 57;
   */
  L_ROOKIE_STONE = 57,

  /**
   * 迷你能量武石(綁定)
   *
   * @generated from enum value: TYPE_L_MINI_STONE = 58;
   */
  L_MINI_STONE = 58,

  /**
   * @generated from enum value: TYPE_STONE_END = 59;
   */
  STONE_END = 59,

  /**
   * @generated from enum value: TYPE_WARHEAD_BEGIN = 60;
   */
  WARHEAD_BEGIN = 60,

  /**
   * 超能彈頭
   *
   * @generated from enum value: TYPE_SUPER_WARHEAD = 60;
   */
  SUPER_WARHEAD = 60,

  /**
   * 超能彈頭(綁定)
   *
   * @generated from enum value: TYPE_L_SUPER_WARHEAD = 61;
   */
  L_SUPER_WARHEAD = 61,

  /**
   * 高能彈頭
   *
   * @generated from enum value: TYPE_HIGH_WARHEAD = 62;
   */
  HIGH_WARHEAD = 62,

  /**
   * 高能彈頭(綁定)
   *
   * @generated from enum value: TYPE_L_HIGH_WARHEAD = 63;
   */
  L_HIGH_WARHEAD = 63,

  /**
   * 能量彈頭
   *
   * @generated from enum value: TYPE_WARHEAD = 64;
   */
  WARHEAD = 64,

  /**
   * 能量彈頭(綁定)
   *
   * @generated from enum value: TYPE_L_WARHEAD = 65;
   */
  L_WARHEAD = 65,

  /**
   * @generated from enum value: TYPE_WARHEAD_END = 66;
   */
  WARHEAD_END = 66,

  /**
   * 水晶
   *
   * @generated from enum value: TYPE_CRYSTAL = 70;
   */
  CRYSTAL = 70,
}

/**
 * Describes the enum currency.Type.
 */
export const TypeSchema: GenEnum<Type> = /*@__PURE__*/
  enumDesc(file_gt2_currency_currency, 0);

