// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file service/lobby/lobby.proto (package lobby, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Type } from "../../gt2/currency/currency_pb";
import { file_gt2_currency_currency } from "../../gt2/currency/currency_pb";
import type { ThemeType } from "../../gt2/basicTypes/basicTypes_pb";
import { file_gt2_basicTypes_basicTypes } from "../../gt2/basicTypes/basicTypes_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/lobby/lobby.proto.
 */
export const file_service_lobby_lobby: GenFile = /*@__PURE__*/
  fileDesc("ChlzZXJ2aWNlL2xvYmJ5L2xvYmJ5LnByb3RvEgVsb2JieSKFAQoNQmFzZVRoZW1lSW5mbxIPCgdnYW1lX2lkGAEgASgNEhAKCHRoZW1lX2lkGAIgASgNEhIKCnRoZW1lX25hbWUYAyABKAkSJQoNY3VycmVuY3lfdHlwZRgEIAEoDjIOLmN1cnJlbmN5LlR5cGUSFgoOY3VzdG9tZV9zdGF0dXMYBSABKAkiIQoNRmluZFRoZW1lc1JlcRIQCghnYW1lX2lkcxgBIAMoBSIlChBHYW1lSWNvbkluZm9zUmVxEhEKCXN0YWdlX2lkcxgBIAMoBSJdCg1GaW5kVGhlbWVzQWNrEh0KBnJlc3VsdBgBIAEoDjINLmxvYmJ5LlJlc3VsdBItCg90aGVtZV9pbmZvX2xpc3QYAiADKAsyFC5sb2JieS5CYXNlVGhlbWVJbmZvIo0CCg5HYW1lSWNvblN0YXR1cxINCgVvcmRlchgBIAEoBRIPCgdnYW1lX2lkGAIgASgNEikKCnRoZW1lX3R5cGUYAyABKA4yFS5iYXNpY1R5cGVzLlRoZW1lVHlwZRIRCglpY29uX3R5cGUYBCABKA0SDgoGc3RhdHVzGAUgASgDEgsKA3JlcxgGIAEoCRIOCgZhY3Rpb24YByABKAUSFAoMYWN0aW9uX3BhcmFtGAggASgJEi0KCXN0YXJ0VGltZRgJIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKwoHZW5kVGltZRgKIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiOgoSR2FtZUljb25TdGF0dXNMaXN0EiQKBWl0ZW1zGAEgAygLMhUubG9iYnkuR2FtZUljb25TdGF0dXMiqwEKD0dhbWVJY29uSW5mb0FjaxIdCgZyZXN1bHQYASABKA4yDS5sb2JieS5SZXN1bHQSMAoFaW5mb3MYAiADKAsyIS5sb2JieS5HYW1lSWNvbkluZm9BY2suSW5mb3NFbnRyeRpHCgpJbmZvc0VudHJ5EgsKA2tleRgBIAEoBRIoCgV2YWx1ZRgCIAEoCzIZLmxvYmJ5LkdhbWVJY29uU3RhdHVzTGlzdDoCOAEqZgoGUmVzdWx0EhEKDVJFU1VMVF9SRVFfT0sQABISCg5SRVNVTFRfUkVRX0VSUhABEhkKFVJFU1VMVF9SRVFfRlJFUVVFTlRMWRACEhoKFlJFU1VMVF9SRVFfUkVESVNfRVJST1IQAypNCgNVMlMSDwoLVTJTX1VOS05PV04QABIYChRVMlNfRklORF9HQU1FX1RIRU1FUxABEhsKF1UyU19SRVFfR0FNRV9JQ09OX0lORk9TEAIqTQoDUzJVEg8KC1MyVV9VTktOT1dOEAASGAoUUzJVX0ZJTkRfR0FNRV9USEVNRVMQARIbChdTMlVfQUNLX0dBTUVfSUNPTl9JTkZPUxACQmsKCWNvbS5sb2JieUIKTG9iYnlQcm90b1ABWh5wcm90b2NvbC9zZXJ2aWNlL2xvYmJ5O2xvYmJ5UGKiAgNMWFiqAgVMb2JiecoCBUxvYmJ54gIRTG9iYnlcR1BCTWV0YWRhdGHqAgVMb2JieWIGcHJvdG8z", [file_gt2_currency_currency, file_gt2_basicTypes_basicTypes, file_google_protobuf_timestamp]);

/**
 * -----------------------------------------------------------------------------
 * 基礎訊息定義 (Base Message Definitions)
 * -----------------------------------------------------------------------------
 * 廳館資訊 (基於 C++ ThemeInfoV2)
 *
 * @generated from message lobby.BaseThemeInfo
 */
export type BaseThemeInfo = Message<"lobby.BaseThemeInfo"> & {
  /**
   * 遊戲 ID
   *
   * @generated from field: uint32 game_id = 1;
   */
  gameId: number;

  /**
   * 廳館 ID	
   *
   * @generated from field: uint32 theme_id = 2;
   */
  themeId: number;

  /**
   * 廳館名稱
   *
   * @generated from field: string theme_name = 3;
   */
  themeName: string;

  /**
   * 幣別	
   *
   * @generated from field: currency.Type currency_type = 4;
   */
  currencyType: Type;

  /**
   * 各遊戲自定義狀態
   *
   * @generated from field: string custome_status = 5;
   */
  customeStatus: string;
};

/**
 * Describes the message lobby.BaseThemeInfo.
 * Use `create(BaseThemeInfoSchema)` to create a new message.
 */
export const BaseThemeInfoSchema: GenMessage<BaseThemeInfo> = /*@__PURE__*/
  messageDesc(file_service_lobby_lobby, 0);

/**
 * 要求廳館資訊列表
 *
 * @generated from message lobby.FindThemesReq
 */
export type FindThemesReq = Message<"lobby.FindThemesReq"> & {
  /**
   * 遊戲ID列表
   *
   * @generated from field: repeated int32 game_ids = 1;
   */
  gameIds: number[];
};

/**
 * Describes the message lobby.FindThemesReq.
 * Use `create(FindThemesReqSchema)` to create a new message.
 */
export const FindThemesReqSchema: GenMessage<FindThemesReq> = /*@__PURE__*/
  messageDesc(file_service_lobby_lobby, 1);

/**
 * 使用 ClientStage 要求廳館列表請求	
 *
 * @generated from message lobby.GameIconInfosReq
 */
export type GameIconInfosReq = Message<"lobby.GameIconInfosReq"> & {
  /**
   * 客戶端階段列表
   *
   * @generated from field: repeated int32 stage_ids = 1;
   */
  stageIds: number[];
};

/**
 * Describes the message lobby.GameIconInfosReq.
 * Use `create(GameIconInfosReqSchema)` to create a new message.
 */
export const GameIconInfosReqSchema: GenMessage<GameIconInfosReq> = /*@__PURE__*/
  messageDesc(file_service_lobby_lobby, 2);

/**
 * 廳館資訊結果
 *
 * @generated from message lobby.FindThemesAck
 */
export type FindThemesAck = Message<"lobby.FindThemesAck"> & {
  /**
   * 結果
   *
   * @generated from field: lobby.Result result = 1;
   */
  result: Result;

  /**
   * 資料List
   *
   * @generated from field: repeated lobby.BaseThemeInfo theme_info_list = 2;
   */
  themeInfoList: BaseThemeInfo[];
};

/**
 * Describes the message lobby.FindThemesAck.
 * Use `create(FindThemesAckSchema)` to create a new message.
 */
export const FindThemesAckSchema: GenMessage<FindThemesAck> = /*@__PURE__*/
  messageDesc(file_service_lobby_lobby, 3);

/**
 * -----------------------------------------------------------------------------
 * 遊戲圖示資訊回應訊息 (Game Icon Info Response Messages)
 * -----------------------------------------------------------------------------
 * 廳館遊戲圖示狀態
 *
 * @generated from message lobby.GameIconStatus
 */
export type GameIconStatus = Message<"lobby.GameIconStatus"> & {
  /**
   * 排序
   *
   * @generated from field: int32 order = 1;
   */
  order: number;

  /**
   * gt2.GameId
   *
   * @generated from field: uint32 game_id = 2;
   */
  gameId: number;

  /**
   * 廳館類型
   *
   * @generated from field: basicTypes.ThemeType theme_type = 3;
   */
  themeType: ThemeType;

  /**
   * iconType
   *
   * @generated from field: uint32 icon_type = 4;
   */
  iconType: number;

  /**
   * iconStatus
   *
   * @generated from field: int64 status = 5;
   */
  status: bigint;

  /**
   * 客戶端資源
   *
   * @generated from field: string res = 6;
   */
  res: string;

  /**
   * Client處理
   *
   * @generated from field: int32 action = 7;
   */
  action: number;

  /**
   * Client處理參數
   *
   * @generated from field: string action_param = 8;
   */
  actionParam: string;

  /**
   * 開始時間
   *
   * @generated from field: google.protobuf.Timestamp startTime = 9;
   */
  startTime?: Timestamp;

  /**
   * 結束時間
   *
   * @generated from field: google.protobuf.Timestamp endTime = 10;
   */
  endTime?: Timestamp;
};

/**
 * Describes the message lobby.GameIconStatus.
 * Use `create(GameIconStatusSchema)` to create a new message.
 */
export const GameIconStatusSchema: GenMessage<GameIconStatus> = /*@__PURE__*/
  messageDesc(file_service_lobby_lobby, 4);

/**
 * 廳館遊戲圖示狀態列表
 *
 * @generated from message lobby.GameIconStatusList
 */
export type GameIconStatusList = Message<"lobby.GameIconStatusList"> & {
  /**
   * @generated from field: repeated lobby.GameIconStatus items = 1;
   */
  items: GameIconStatus[];
};

/**
 * Describes the message lobby.GameIconStatusList.
 * Use `create(GameIconStatusListSchema)` to create a new message.
 */
export const GameIconStatusListSchema: GenMessage<GameIconStatusList> = /*@__PURE__*/
  messageDesc(file_service_lobby_lobby, 5);

/**
 * 遊戲圖示資訊回應
 *
 * @generated from message lobby.GameIconInfoAck
 */
export type GameIconInfoAck = Message<"lobby.GameIconInfoAck"> & {
  /**
   * 結果
   *
   * @generated from field: lobby.Result result = 1;
   */
  result: Result;

  /**
   * <參考Client StageId, GameIconStatusList>
   *
   * @generated from field: map<int32, lobby.GameIconStatusList> infos = 2;
   */
  infos: { [key: number]: GameIconStatusList };
};

/**
 * Describes the message lobby.GameIconInfoAck.
 * Use `create(GameIconInfoAckSchema)` to create a new message.
 */
export const GameIconInfoAckSchema: GenMessage<GameIconInfoAck> = /*@__PURE__*/
  messageDesc(file_service_lobby_lobby, 6);

/**
 * 廳館列表請求結果
 *
 * @generated from enum lobby.Result
 */
export enum Result {
  /**
   * 正常
   *
   * @generated from enum value: RESULT_REQ_OK = 0;
   */
  REQ_OK = 0,

  /**
   * 錯誤
   *
   * @generated from enum value: RESULT_REQ_ERR = 1;
   */
  REQ_ERR = 1,

  /**
   * 頻繁
   *
   * @generated from enum value: RESULT_REQ_FREQUENTLY = 2;
   */
  REQ_FREQUENTLY = 2,

  /**
   * Redis錯誤
   *
   * @generated from enum value: RESULT_REQ_REDIS_ERROR = 3;
   */
  REQ_REDIS_ERROR = 3,
}

/**
 * Describes the enum lobby.Result.
 */
export const ResultSchema: GenEnum<Result> = /*@__PURE__*/
  enumDesc(file_service_lobby_lobby, 0);

/**
 * 玩家要求協定 (U2S - User to Server)
 *
 * @generated from enum lobby.U2S
 */
export enum U2S {
  /**
   * 未知
   *
   * @generated from enum value: U2S_UNKNOWN = 0;
   */
  U2S_UNKNOWN = 0,

  /**
   * 玩家要求廳館列表					(FindThemesReq)
   *
   * @generated from enum value: U2S_FIND_GAME_THEMES = 1;
   */
  U2S_FIND_GAME_THEMES = 1,

  /**
   * 玩家要求取得遊戲Icon資訊			(GameIconInfosReq)
   *
   * @generated from enum value: U2S_REQ_GAME_ICON_INFOS = 2;
   */
  U2S_REQ_GAME_ICON_INFOS = 2,
}

/**
 * Describes the enum lobby.U2S.
 */
export const U2SSchema: GenEnum<U2S> = /*@__PURE__*/
  enumDesc(file_service_lobby_lobby, 1);

/**
 * 伺服器回應協定 (S2U - Server to User)
 *
 * @generated from enum lobby.S2U
 */
export enum S2U {
  /**
   * 未知
   *
   * @generated from enum value: S2U_UNKNOWN = 0;
   */
  S2U_UNKNOWN = 0,

  /**
   * 回應玩家廳館列表
   *
   * @generated from enum value: S2U_FIND_GAME_THEMES = 1;
   */
  S2U_FIND_GAME_THEMES = 1,

  /**
   * 回應玩家遊戲Icon資訊列表
   *
   * @generated from enum value: S2U_ACK_GAME_ICON_INFOS = 2;
   */
  S2U_ACK_GAME_ICON_INFOS = 2,
}

/**
 * Describes the enum lobby.S2U.
 */
export const S2USchema: GenEnum<S2U> = /*@__PURE__*/
  enumDesc(file_service_lobby_lobby, 2);

