// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file gt2/list.proto (package gt2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gt2/list.proto.
 */
export const file_gt2_list: GenFile = /*@__PURE__*/
  fileDesc("Cg5ndDIvbGlzdC5wcm90bxIDZ3QyIhwKCkRvdWJsZUxpc3QSDgoGdmFsdWVzGAEgAygBIhsKCUZsb2F0TGlzdBIOCgZ2YWx1ZXMYASADKAIiGwoJSW50MzJMaXN0Eg4KBnZhbHVlcxgBIAMoBSIbCglJbnQ2NExpc3QSDgoGdmFsdWVzGAEgAygDIhwKClVpbnQzMkxpc3QSDgoGdmFsdWVzGAEgAygNIhwKClVpbnQ2NExpc3QSDgoGdmFsdWVzGAEgAygEIhoKCEJvb2xMaXN0Eg4KBnZhbHVlcxgBIAMoCCIcCgpTdHJpbmdMaXN0Eg4KBnZhbHVlcxgBIAMoCUJUCgdjb20uZ3QyQglMaXN0UHJvdG9QAVoScHJvdG9jb2wvZ3QyO2d0MlBiogIDR1hYqgIDR3QyygIDR3Qy4gIPR3QyXEdQQk1ldGFkYXRh6gIDR3QyYgZwcm90bzM");

/**
 * @generated from message gt2.DoubleList
 */
export type DoubleList = Message<"gt2.DoubleList"> & {
  /**
   * @generated from field: repeated double values = 1;
   */
  values: number[];
};

/**
 * Describes the message gt2.DoubleList.
 * Use `create(DoubleListSchema)` to create a new message.
 */
export const DoubleListSchema: GenMessage<DoubleList> = /*@__PURE__*/
  messageDesc(file_gt2_list, 0);

/**
 * @generated from message gt2.FloatList
 */
export type FloatList = Message<"gt2.FloatList"> & {
  /**
   * @generated from field: repeated float values = 1;
   */
  values: number[];
};

/**
 * Describes the message gt2.FloatList.
 * Use `create(FloatListSchema)` to create a new message.
 */
export const FloatListSchema: GenMessage<FloatList> = /*@__PURE__*/
  messageDesc(file_gt2_list, 1);

/**
 * @generated from message gt2.Int32List
 */
export type Int32List = Message<"gt2.Int32List"> & {
  /**
   * @generated from field: repeated int32 values = 1;
   */
  values: number[];
};

/**
 * Describes the message gt2.Int32List.
 * Use `create(Int32ListSchema)` to create a new message.
 */
export const Int32ListSchema: GenMessage<Int32List> = /*@__PURE__*/
  messageDesc(file_gt2_list, 2);

/**
 * @generated from message gt2.Int64List
 */
export type Int64List = Message<"gt2.Int64List"> & {
  /**
   * @generated from field: repeated int64 values = 1;
   */
  values: bigint[];
};

/**
 * Describes the message gt2.Int64List.
 * Use `create(Int64ListSchema)` to create a new message.
 */
export const Int64ListSchema: GenMessage<Int64List> = /*@__PURE__*/
  messageDesc(file_gt2_list, 3);

/**
 * @generated from message gt2.Uint32List
 */
export type Uint32List = Message<"gt2.Uint32List"> & {
  /**
   * @generated from field: repeated uint32 values = 1;
   */
  values: number[];
};

/**
 * Describes the message gt2.Uint32List.
 * Use `create(Uint32ListSchema)` to create a new message.
 */
export const Uint32ListSchema: GenMessage<Uint32List> = /*@__PURE__*/
  messageDesc(file_gt2_list, 4);

/**
 * @generated from message gt2.Uint64List
 */
export type Uint64List = Message<"gt2.Uint64List"> & {
  /**
   * @generated from field: repeated uint64 values = 1;
   */
  values: bigint[];
};

/**
 * Describes the message gt2.Uint64List.
 * Use `create(Uint64ListSchema)` to create a new message.
 */
export const Uint64ListSchema: GenMessage<Uint64List> = /*@__PURE__*/
  messageDesc(file_gt2_list, 5);

/**
 * @generated from message gt2.BoolList
 */
export type BoolList = Message<"gt2.BoolList"> & {
  /**
   * @generated from field: repeated bool values = 1;
   */
  values: boolean[];
};

/**
 * Describes the message gt2.BoolList.
 * Use `create(BoolListSchema)` to create a new message.
 */
export const BoolListSchema: GenMessage<BoolList> = /*@__PURE__*/
  messageDesc(file_gt2_list, 6);

/**
 * @generated from message gt2.StringList
 */
export type StringList = Message<"gt2.StringList"> & {
  /**
   * @generated from field: repeated string values = 1;
   */
  values: string[];
};

/**
 * Describes the message gt2.StringList.
 * Use `create(StringListSchema)` to create a new message.
 */
export const StringListSchema: GenMessage<StringList> = /*@__PURE__*/
  messageDesc(file_gt2_list, 7);

