// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file service/finance/finance.proto (package finance, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Type } from "../../gt2/currency/currency_pb";
import { file_gt2_currency_currency } from "../../gt2/currency/currency_pb";
import type { Prize as Prize$1 } from "../../gt2/prize/prize_pb";
import { file_gt2_prize_prize } from "../../gt2/prize/prize_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/finance/finance.proto.
 */
export const file_service_finance_finance: GenFile = /*@__PURE__*/
  fileDesc("Ch1zZXJ2aWNlL2ZpbmFuY2UvZmluYW5jZS5wcm90bxIHZmluYW5jZSI4Cg5XYXJoZWFkTW9kZVJlcRImCg5jdXJyZW5jeV90eXBlcxgBIAMoDjIOLmN1cnJlbmN5LlR5cGUiOAoOV2FyaGVhZE1vZGVBY2sSJgoOY3VycmVuY3lfdHlwZXMYASADKA4yDi5jdXJyZW5jeS5UeXBlIjcKCFByaXplUmVxEisKE2F1dG9fY3VycmVuY3lfdHlwZXMYASADKA4yDi5jdXJyZW5jeS5UeXBlIioKCFByaXplQWNrEh4KBnByaXplcxgBIAMoCzIOLmZpbmFuY2UuUHJpemUi7gEKBVByaXplEgoKAmlkGAEgASgEEhsKBXByaXplGAIgASgLMgwucHJpemUuUHJpemUSDwoHaGFzX2dvdBgDIAEoCBIOCgZzb3VyY2UYBCABKAkSMAoMY3JlYXRlZF90aW1lGAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIsCghnb3RfdGltZRgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLAoIZW5kX3RpbWUYByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEg0KBWV4dHJhGAggASgFIh4KD1JlY2VpdmVQcml6ZVJlcRILCgNpZHMYASADKAQipQIKD1JlY2VpdmVQcml6ZUFjaxIwCgdyZXN1bHRzGAEgAygLMh8uZmluYW5jZS5SZWNlaXZlUHJpemVBY2suUmVzdWx0Gt8BCgZSZXN1bHQSEAoIcHJpemVfaWQYASABKAQSNgoGc3RhdHVzGAIgASgOMiYuZmluYW5jZS5SZWNlaXZlUHJpemVBY2suUmVzdWx0LlN0YXR1cyKKAQoGU3RhdHVzEhIKDlNUQVRVU19VTktOT1dOEAASDQoJU1RBVFVTX09LEAESFgoSU1RBVFVTX1JFRElTX0VSUk9SEAISEwoPU1RBVFVTX0RCX0VSUk9SEAMSGAoUU1RBVFVTX0lOVkFMSURfSU5ERVgQBBIWChJTVEFUVVNfQUxSRUFEWV9HT1QQBSKRAQoLU3RvcmVkVmFsdWUSEgoKYWNjb3VudF9pZBgBIAEoDRIbCgVwcml6ZRgCIAEoCzIMLnByaXplLlByaXplEhMKC3NvdXJjZV9nYW1lGAMgASgFEhUKDXJlY2VpdmVkX2dhbWUYBCABKAUSEQoJYnVuZGxlX2lkGAUgASgJEhIKCnByb2R1Y3RfaWQYBiABKAkiOAoQU3RvcmVkVmFsdWVOb3RpZhIkCgZ2YWx1ZXMYASADKAsyFC5maW5hbmNlLlN0b3JlZFZhbHVlKlIKA1UyUxIPCgtVMlNfVU5LTk9XThAAEhQKEFUyU19XQVJIRUFEX01PREUQARINCglVMlNfUFJJWkUQAhIVChFVMlNfUkVDRUlWRV9QUklaRRADKmgKA1MyVRIPCgtTMlVfVU5LTk9XThAAEhQKEFMyVV9XQVJIRUFEX01PREUQARINCglTMlVfUFJJWkUQAhIVChFTMlVfUkVDRUlWRV9QUklaRRADEhQKEFMyVV9TVE9SRURfVkFMVUUQBEJ7Cgtjb20uZmluYW5jZUIMRmluYW5jZVByb3RvUAFaInByb3RvY29sL3NlcnZpY2UvZmluYW5jZTtmaW5hbmNlUGKiAgNGWFiqAgdGaW5hbmNlygIHRmluYW5jZeICE0ZpbmFuY2VcR1BCTWV0YWRhdGHqAgdGaW5hbmNlYgZwcm90bzM", [file_gt2_currency_currency, file_gt2_prize_prize, file_google_protobuf_timestamp]);

/**
 * @generated from message finance.WarheadModeReq
 */
export type WarheadModeReq = Message<"finance.WarheadModeReq"> & {
  /**
   * @generated from field: repeated currency.Type currency_types = 1;
   */
  currencyTypes: Type[];
};

/**
 * Describes the message finance.WarheadModeReq.
 * Use `create(WarheadModeReqSchema)` to create a new message.
 */
export const WarheadModeReqSchema: GenMessage<WarheadModeReq> = /*@__PURE__*/
  messageDesc(file_service_finance_finance, 0);

/**
 * @generated from message finance.WarheadModeAck
 */
export type WarheadModeAck = Message<"finance.WarheadModeAck"> & {
  /**
   * @generated from field: repeated currency.Type currency_types = 1;
   */
  currencyTypes: Type[];
};

/**
 * Describes the message finance.WarheadModeAck.
 * Use `create(WarheadModeAckSchema)` to create a new message.
 */
export const WarheadModeAckSchema: GenMessage<WarheadModeAck> = /*@__PURE__*/
  messageDesc(file_service_finance_finance, 1);

/**
 * @generated from message finance.PrizeReq
 */
export type PrizeReq = Message<"finance.PrizeReq"> & {
  /**
   * 自動領取貨幣類型
   *
   * @generated from field: repeated currency.Type auto_currency_types = 1;
   */
  autoCurrencyTypes: Type[];
};

/**
 * Describes the message finance.PrizeReq.
 * Use `create(PrizeReqSchema)` to create a new message.
 */
export const PrizeReqSchema: GenMessage<PrizeReq> = /*@__PURE__*/
  messageDesc(file_service_finance_finance, 2);

/**
 * @generated from message finance.PrizeAck
 */
export type PrizeAck = Message<"finance.PrizeAck"> & {
  /**
   * @generated from field: repeated finance.Prize prizes = 1;
   */
  prizes: Prize[];
};

/**
 * Describes the message finance.PrizeAck.
 * Use `create(PrizeAckSchema)` to create a new message.
 */
export const PrizeAckSchema: GenMessage<PrizeAck> = /*@__PURE__*/
  messageDesc(file_service_finance_finance, 3);

/**
 * @generated from message finance.Prize
 */
export type Prize = Message<"finance.Prize"> & {
  /**
   * prizeId
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: prize.Prize prize = 2;
   */
  prize?: Prize$1;

  /**
   * @generated from field: bool has_got = 3;
   */
  hasGot: boolean;

  /**
   * @generated from field: string source = 4;
   */
  source: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_time = 5;
   */
  createdTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp got_time = 6;
   */
  gotTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 7;
   */
  endTime?: Timestamp;

  /**
   * @generated from field: int32 extra = 8;
   */
  extra: number;
};

/**
 * Describes the message finance.Prize.
 * Use `create(PrizeSchema)` to create a new message.
 */
export const PrizeSchema: GenMessage<Prize> = /*@__PURE__*/
  messageDesc(file_service_finance_finance, 4);

/**
 * @generated from message finance.ReceivePrizeReq
 */
export type ReceivePrizeReq = Message<"finance.ReceivePrizeReq"> & {
  /**
   * prizeId
   *
   * @generated from field: repeated uint64 ids = 1;
   */
  ids: bigint[];
};

/**
 * Describes the message finance.ReceivePrizeReq.
 * Use `create(ReceivePrizeReqSchema)` to create a new message.
 */
export const ReceivePrizeReqSchema: GenMessage<ReceivePrizeReq> = /*@__PURE__*/
  messageDesc(file_service_finance_finance, 5);

/**
 * @generated from message finance.ReceivePrizeAck
 */
export type ReceivePrizeAck = Message<"finance.ReceivePrizeAck"> & {
  /**
   * @generated from field: repeated finance.ReceivePrizeAck.Result results = 1;
   */
  results: ReceivePrizeAck_Result[];
};

/**
 * Describes the message finance.ReceivePrizeAck.
 * Use `create(ReceivePrizeAckSchema)` to create a new message.
 */
export const ReceivePrizeAckSchema: GenMessage<ReceivePrizeAck> = /*@__PURE__*/
  messageDesc(file_service_finance_finance, 6);

/**
 * @generated from message finance.ReceivePrizeAck.Result
 */
export type ReceivePrizeAck_Result = Message<"finance.ReceivePrizeAck.Result"> & {
  /**
   * prizeId
   *
   * @generated from field: uint64 prize_id = 1;
   */
  prizeId: bigint;

  /**
   * @generated from field: finance.ReceivePrizeAck.Result.Status status = 2;
   */
  status: ReceivePrizeAck_Result_Status;
};

/**
 * Describes the message finance.ReceivePrizeAck.Result.
 * Use `create(ReceivePrizeAck_ResultSchema)` to create a new message.
 */
export const ReceivePrizeAck_ResultSchema: GenMessage<ReceivePrizeAck_Result> = /*@__PURE__*/
  messageDesc(file_service_finance_finance, 6, 0);

/**
 * @generated from enum finance.ReceivePrizeAck.Result.Status
 */
export enum ReceivePrizeAck_Result_Status {
  /**
   * @generated from enum value: STATUS_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * 領取成功
   *
   * @generated from enum value: STATUS_OK = 1;
   */
  OK = 1,

  /**
   * 無法更新Redis
   *
   * @generated from enum value: STATUS_REDIS_ERROR = 2;
   */
  REDIS_ERROR = 2,

  /**
   * 無法更新DB
   *
   * @generated from enum value: STATUS_DB_ERROR = 3;
   */
  DB_ERROR = 3,

  /**
   * 無效編號（使用者或獎品）、獎品過期
   *
   * @generated from enum value: STATUS_INVALID_INDEX = 4;
   */
  INVALID_INDEX = 4,

  /**
   * 該獎品已領過
   *
   * @generated from enum value: STATUS_ALREADY_GOT = 5;
   */
  ALREADY_GOT = 5,
}

/**
 * Describes the enum finance.ReceivePrizeAck.Result.Status.
 */
export const ReceivePrizeAck_Result_StatusSchema: GenEnum<ReceivePrizeAck_Result_Status> = /*@__PURE__*/
  enumDesc(file_service_finance_finance, 6, 0, 0);

/**
 * @generated from message finance.StoredValue
 */
export type StoredValue = Message<"finance.StoredValue"> & {
  /**
   * gt2.AccountId
   *
   * @generated from field: uint32 account_id = 1;
   */
  accountId: number;

  /**
   * *prize.Prize
   *
   * @generated from field: prize.Prize prize = 2;
   */
  prize?: Prize$1;

  /**
   * gt2.GameKind
   *
   * @generated from field: int32 source_game = 3;
   */
  sourceGame: number;

  /**
   * gt2.GameKind
   *
   * @generated from field: int32 received_game = 4;
   */
  receivedGame: number;

  /**
   * gt2.BundleId
   *
   * @generated from field: string bundle_id = 5;
   */
  bundleId: string;

  /**
   * gt2.ProductId
   *
   * @generated from field: string product_id = 6;
   */
  productId: string;
};

/**
 * Describes the message finance.StoredValue.
 * Use `create(StoredValueSchema)` to create a new message.
 */
export const StoredValueSchema: GenMessage<StoredValue> = /*@__PURE__*/
  messageDesc(file_service_finance_finance, 7);

/**
 * @generated from message finance.StoredValueNotif
 */
export type StoredValueNotif = Message<"finance.StoredValueNotif"> & {
  /**
   * @generated from field: repeated finance.StoredValue values = 1;
   */
  values: StoredValue[];
};

/**
 * Describes the message finance.StoredValueNotif.
 * Use `create(StoredValueNotifSchema)` to create a new message.
 */
export const StoredValueNotifSchema: GenMessage<StoredValueNotif> = /*@__PURE__*/
  messageDesc(file_service_finance_finance, 8);

/**
 * @generated from enum finance.U2S
 */
export enum U2S {
  /**
   * @generated from enum value: U2S_UNKNOWN = 0;
   */
  U2S_UNKNOWN = 0,

  /**
   * WarheadModeReq
   *
   * @generated from enum value: U2S_WARHEAD_MODE = 1;
   */
  U2S_WARHEAD_MODE = 1,

  /**
   * PrizeReq
   *
   * @generated from enum value: U2S_PRIZE = 2;
   */
  U2S_PRIZE = 2,

  /**
   * ReceivePrizeReq
   *
   * @generated from enum value: U2S_RECEIVE_PRIZE = 3;
   */
  U2S_RECEIVE_PRIZE = 3,
}

/**
 * Describes the enum finance.U2S.
 */
export const U2SSchema: GenEnum<U2S> = /*@__PURE__*/
  enumDesc(file_service_finance_finance, 0);

/**
 * @generated from enum finance.S2U
 */
export enum S2U {
  /**
   * @generated from enum value: S2U_UNKNOWN = 0;
   */
  S2U_UNKNOWN = 0,

  /**
   * WarheadModeAck
   *
   * @generated from enum value: S2U_WARHEAD_MODE = 1;
   */
  S2U_WARHEAD_MODE = 1,

  /**
   * PrizeAck
   *
   * @generated from enum value: S2U_PRIZE = 2;
   */
  S2U_PRIZE = 2,

  /**
   * ReceivePrizeAck
   *
   * @generated from enum value: S2U_RECEIVE_PRIZE = 3;
   */
  S2U_RECEIVE_PRIZE = 3,

  /**
   * StoredValueNotif
   *
   * @generated from enum value: S2U_STORED_VALUE = 4;
   */
  S2U_STORED_VALUE = 4,
}

/**
 * Describes the enum finance.S2U.
 */
export const S2USchema: GenEnum<S2U> = /*@__PURE__*/
  enumDesc(file_service_finance_finance, 1);

