// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file service/webConsumption/webConsumption.proto (package webConsumption, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Prize } from "../../gt2/prize/prize_pb";
import { file_gt2_prize_prize } from "../../gt2/prize/prize_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/webConsumption/webConsumption.proto.
 */
export const file_service_webConsumption_webConsumption: GenFile = /*@__PURE__*/
  fileDesc("CitzZXJ2aWNlL3dlYkNvbnN1bXB0aW9uL3dlYkNvbnN1bXB0aW9uLnByb3RvEg53ZWJDb25zdW1wdGlvbiJRCglQcml6ZUluZm8SGwoFcHJpemUYASABKAsyDC5wcml6ZS5Qcml6ZRISCgpwcml6ZV9uYW1lGAIgASgJEhMKC2FjdGl2ZV9uYW1lGAMgASgJIj4KDVdlYlByaXplUmVwbHkSLQoKcHJpemVfbGlzdBgBIAMoCzIZLndlYkNvbnN1bXB0aW9uLlByaXplSW5mbyJACg9XZWJQcml6ZVJlcXVlc3QSLQoId2ViX3R5cGUYASABKA4yGy53ZWJDb25zdW1wdGlvbi5XZWJJdGVtVHlwZSLKAQoLV2ViUHJpemVMb2cSEgoKYWNjb3VudF9pZBgBIAEoBRISCgppdGVtX2luZGV4GAIgASgJEhYKDnByaXplX2V4dHJhX25vGAMgASgFEg4KBmFtb3VudBgEIAEoBRISCgpwcml6ZV9uYW1lGAUgASgJEigKBHRpbWUYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi0KCHdlYl90eXBlGAcgASgOMhsud2ViQ29uc3VtcHRpb24uV2ViSXRlbVR5cGUiFgoUTm90aWZ5RGVwb3NpdFN1Y2Nlc3MqWQoDVTJTEg8KC1UyU19VTktOT1dOEAASHgoaVTJTX1dFQl9SRVFVRVNUX1BSSVpFX0lORk8QARIhCh1VMlNfV0VCX0JQX1JFUVVFU1RfUFJJWkVfSU5GTxACKoQBCgNTMlUSDwoLUzJVX1VOS05PV04QABIgChxTMlVfV0VCX1JFUExZX1BSSVpFX0lORk9fQUNLEAESIwofUzJVX1dFQl9CUF9SRVBMWV9QUklaRV9JTkZPX0FDSxACEiUKIVMyVV9XRUJfQlBfTk9USUZZX0RFUE9TSVRfU1VDQ0VTUxADKoEBCgtXZWJJdGVtVHlwZRIWChJXRUJfSVRFTV9UWVBFX05VTEwQABIbChdXRUJfSVRFTV9UWVBFX1dFQl9QT0lOVBABEh4KGldFQl9JVEVNX1RZUEVfV0VOX0JQX1BPSU5UEAISHQoZV0VCX0lURU1fVFlQRV9NSl9BQ1RJVklUWRADQrMBChJjb20ud2ViQ29uc3VtcHRpb25CE1dlYkNvbnN1bXB0aW9uUHJvdG9QAVowcHJvdG9jb2wvc2VydmljZS93ZWJDb25zdW1wdGlvbjt3ZWJDb25zdW1wdGlvblBiogIDV1hYqgIOV2ViQ29uc3VtcHRpb27KAg5XZWJDb25zdW1wdGlvbuICGldlYkNvbnN1bXB0aW9uXEdQQk1ldGFkYXRh6gIOV2ViQ29uc3VtcHRpb25iBnByb3RvMw", [file_google_protobuf_timestamp, file_gt2_prize_prize]);

/**
 * *
 * 獎勵資訊 (使用標準 prize.Prize + 額外資訊)
 *
 * @generated from message webConsumption.PrizeInfo
 */
export type PrizeInfo = Message<"webConsumption.PrizeInfo"> & {
  /**
   * 獎勵資訊（使用標準 Prize 結構）
   *
   * @generated from field: prize.Prize prize = 1;
   */
  prize?: Prize;

  /**
   * 獎品名稱（用於顯示）
   *
   * @generated from field: string prize_name = 2;
   */
  prizeName: string;

  /**
   * 活動名稱
   *
   * @generated from field: string active_name = 3;
   */
  activeName: string;
};

/**
 * Describes the message webConsumption.PrizeInfo.
 * Use `create(PrizeInfoSchema)` to create a new message.
 */
export const PrizeInfoSchema: GenMessage<PrizeInfo> = /*@__PURE__*/
  messageDesc(file_service_webConsumption_webConsumption, 0);

/**
 * *
 * 網頁獎勵回覆 (對應 C++ 的 SequenceCommandSender<AioPrizeAckBase>)
 *
 * @generated from message webConsumption.WebPrizeReply
 */
export type WebPrizeReply = Message<"webConsumption.WebPrizeReply"> & {
  /**
   * 獎勵列表
   *
   * @generated from field: repeated webConsumption.PrizeInfo prize_list = 1;
   */
  prizeList: PrizeInfo[];
};

/**
 * Describes the message webConsumption.WebPrizeReply.
 * Use `create(WebPrizeReplySchema)` to create a new message.
 */
export const WebPrizeReplySchema: GenMessage<WebPrizeReply> = /*@__PURE__*/
  messageDesc(file_service_webConsumption_webConsumption, 1);

/**
 * *
 * 網頁獎勵請求
 *
 * @generated from message webConsumption.WebPrizeRequest
 */
export type WebPrizeRequest = Message<"webConsumption.WebPrizeRequest"> & {
  /**
   * 網頁類型
   *
   * @generated from field: webConsumption.WebItemType web_type = 1;
   */
  webType: WebItemType;
};

/**
 * Describes the message webConsumption.WebPrizeRequest.
 * Use `create(WebPrizeRequestSchema)` to create a new message.
 */
export const WebPrizeRequestSchema: GenMessage<WebPrizeRequest> = /*@__PURE__*/
  messageDesc(file_service_webConsumption_webConsumption, 2);

/**
 * *
 * 網頁獎勵日誌
 *
 * @generated from message webConsumption.WebPrizeLog
 */
export type WebPrizeLog = Message<"webConsumption.WebPrizeLog"> & {
  /**
   * 帳號ID
   *
   * @generated from field: int32 account_id = 1;
   */
  accountId: number;

  /**
   * 道具代碼
   *
   * @generated from field: string item_index = 2;
   */
  itemIndex: string;

  /**
   * 額外編號
   *
   * @generated from field: int32 prize_extra_no = 3;
   */
  prizeExtraNo: number;

  /**
   * 數量
   *
   * @generated from field: int32 amount = 4;
   */
  amount: number;

  /**
   * 獎品名稱
   *
   * @generated from field: string prize_name = 5;
   */
  prizeName: string;

  /**
   * 時間
   *
   * @generated from field: google.protobuf.Timestamp time = 6;
   */
  time?: Timestamp;

  /**
   * 網頁類型
   *
   * @generated from field: webConsumption.WebItemType web_type = 7;
   */
  webType: WebItemType;
};

/**
 * Describes the message webConsumption.WebPrizeLog.
 * Use `create(WebPrizeLogSchema)` to create a new message.
 */
export const WebPrizeLogSchema: GenMessage<WebPrizeLog> = /*@__PURE__*/
  messageDesc(file_service_webConsumption_webConsumption, 3);

/**
 * *
 * 通知儲值成功 (空消息)
 *
 * 空消息，僅用於通知
 *
 * @generated from message webConsumption.NotifyDepositSuccess
 */
export type NotifyDepositSuccess = Message<"webConsumption.NotifyDepositSuccess"> & {
};

/**
 * Describes the message webConsumption.NotifyDepositSuccess.
 * Use `create(NotifyDepositSuccessSchema)` to create a new message.
 */
export const NotifyDepositSuccessSchema: GenMessage<NotifyDepositSuccess> = /*@__PURE__*/
  messageDesc(file_service_webConsumption_webConsumption, 4);

/**
 * U2S 命令 (Client → Server)
 *
 * @generated from enum webConsumption.U2S
 */
export enum U2S {
  /**
   * 未知命令
   *
   * @generated from enum value: U2S_UNKNOWN = 0;
   */
  U2S_UNKNOWN = 0,

  /**
   * None → WebPrizeReply // 請求網頁消費活動獎勵
   *
   * @generated from enum value: U2S_WEB_REQUEST_PRIZE_INFO = 1;
   */
  U2S_WEB_REQUEST_PRIZE_INFO = 1,

  /**
   * None → WebPrizeReply // 請求網頁短BP獎勵
   *
   * @generated from enum value: U2S_WEB_BP_REQUEST_PRIZE_INFO = 2;
   */
  U2S_WEB_BP_REQUEST_PRIZE_INFO = 2,
}

/**
 * Describes the enum webConsumption.U2S.
 */
export const U2SSchema: GenEnum<U2S> = /*@__PURE__*/
  enumDesc(file_service_webConsumption_webConsumption, 0);

/**
 * S2U 命令 (Server → Client)
 *
 * @generated from enum webConsumption.S2U
 */
export enum S2U {
  /**
   * 未知回應
   *
   * @generated from enum value: S2U_UNKNOWN = 0;
   */
  S2U_UNKNOWN = 0,

  /**
   * WebPrizeReply // 回覆網頁消費活動獎勵
   *
   * @generated from enum value: S2U_WEB_REPLY_PRIZE_INFO_ACK = 1;
   */
  S2U_WEB_REPLY_PRIZE_INFO_ACK = 1,

  /**
   * WebPrizeReply // 回覆網頁短BP獎勵
   *
   * @generated from enum value: S2U_WEB_BP_REPLY_PRIZE_INFO_ACK = 2;
   */
  S2U_WEB_BP_REPLY_PRIZE_INFO_ACK = 2,

  /**
   * None // 通知玩家網頁短BP儲值成功
   *
   * @generated from enum value: S2U_WEB_BP_NOTIFY_DEPOSIT_SUCCESS = 3;
   */
  S2U_WEB_BP_NOTIFY_DEPOSIT_SUCCESS = 3,
}

/**
 * Describes the enum webConsumption.S2U.
 */
export const S2USchema: GenEnum<S2U> = /*@__PURE__*/
  enumDesc(file_service_webConsumption_webConsumption, 1);

/**
 * *
 * 網頁獎勵類型 (WebItemType)
 * 引用自 WordCollection 的 WordCollectionWebItemType
 *
 * @generated from enum webConsumption.WebItemType
 */
export enum WebItemType {
  /**
   * 無
   *
   * @generated from enum value: WEB_ITEM_TYPE_NULL = 0;
   */
  NULL = 0,

  /**
   * 網頁活動道具
   *
   * @generated from enum value: WEB_ITEM_TYPE_WEB_POINT = 1;
   */
  WEB_POINT = 1,

  /**
   * 網頁短BP道具
   *
   * @generated from enum value: WEB_ITEM_TYPE_WEN_BP_POINT = 2;
   */
  WEN_BP_POINT = 2,

  /**
   * MJ活動道具
   *
   * @generated from enum value: WEB_ITEM_TYPE_MJ_ACTIVITY = 3;
   */
  MJ_ACTIVITY = 3,
}

/**
 * Describes the enum webConsumption.WebItemType.
 */
export const WebItemTypeSchema: GenEnum<WebItemType> = /*@__PURE__*/
  enumDesc(file_service_webConsumption_webConsumption, 2);

